### ISSUE TITLE
not_home and home in device_tracker usage ?

### ISSUE THREAD

**Issue by saket424** [nebhale/teslamate-discovery#86]
Is the state topic latitude or location. I am confused. Please help with correct syntax
```
- id: '1694297530599'                                                                                                                                                                                       
  alias: WhiteTeslaGarage1EntersHome                                                                                                                                                                        
  description: WhiteTeslaTessYEntersHome                                                                                                                                                                    
  trigger:                                                                                                                                                                                                  
  - platform: state                                                                                                                                                                                         
    entity_id:                                                                                                                                                                                              
    - device_tracker.whitey                                                                                                                                                                                  
    attribute: location                                                                                                                                                                                     
    from: not_home                                                                                                                                                                                          
    to: home                                                                                                                                                                                                
  condition:                                                                                                                                                                                                
  - condition: state                                                                                                                                                                                        
    entity_id: sensor.whitey_shift_state                                                                                                                                                                     
    state: D                                                                                                                                                                                                
  action:                                                                                                                                                                                                   
  - device_id: 77cdb9bf620a4cfcb9988d358179b632                                                                                                                                                             
    domain: cover                                                                                                                                                                                           
    entity_id: 8489b221a3f9d853a4f101b3022e32ab                                                                                                                                                             
    type: open                                                                                                                                                                                          	
```
Is it possible that the state topic and Attribute topic should be /location instead of /latitude ?

```
ha.DeviceTracker{
			Device:                 device,
			Icon:                   "mdi:car",
			JSONAttributesTemplate: fmt.Sprintf(`{{ { "latitude": value | float(0), "longitude": states("sensor.%s_longitude") | float(0) } | to_json }}`, strcase.ToSnake(device.Name)),
			JSONAttributesTopic:    StateTopic(device, "/latitude"),
			Name:                   "",
			SourceType:             "gps",
			StateTopic:             StateTopic(device, "/latitude"),
			UniqueId:               UniqueId(device, "/location"),
			ValueTemplate:          fmt.Sprintf(`{{ "home" if "home" in (states("sensor.%s_geofence") | lower) else "not_home" }}`, strcase.ToSnake(device.Name)),
		},
```
